server:
  port: 8000
shape:
  population:
    amount: 10
    enable: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehousedb
    username: postgres
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
springdoc:
  swagger-ui:
    path: /
    operations-sorter: method
    display-request-duration: true
    try-it-out-enabled: on
